# Generated by Django 4.1.7 on 2023-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_rss_feed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss_feed_database',
            name='publishedDate',
            field=models.DateTimeField(),
        ),
    ]
