# Generated by Django 4.1.7 on 2023-03-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_alter_rss_feed_database_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSS_Feed_Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedName', models.TextField()),
                ('title', models.TextField()),
                ('publishedDate', models.DateTimeField()),
                ('link', models.TextField()),
                ('summary', models.TextField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles(Discarded)',
            },
        ),
    ]
