# Generated by Django 4.1.7 on 2023-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_rss_feed_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss_feed_name_icon',
            name='feedFrequency',
            field=models.IntegerField(default=0),
        ),
    ]
