# Generated by Django 4.1.7 on 2023-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_rss_feed_name_icon_feedfrequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rss_feed_name_icon',
            old_name='feedFrequency',
            new_name='feedFrequency_accepted',
        ),
        migrations.AddField(
            model_name='rss_feed_name_icon',
            name='feedFrequency_reject',
            field=models.IntegerField(default=0),
        ),
    ]
