# Generated by Django 4.1.7 on 2023-03-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_rename_feedfrequency_rss_feed_name_icon_feedfrequency_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss_feed_database',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rss_feed_database',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rss_feed_keyowrds',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rss_feed_keyowrds',
            name='keywords',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rss_feed_name_icon',
            name='feedName',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rss_feed_name_icon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rss_feed_temp',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rss_feed_url',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
