# Generated by Django 4.1.7 on 2023-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0008_alter_rss_feed_database_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss_feed_temp',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rss_feed_url',
            name='feedUrl',
            field=models.TextField(unique=True),
        ),
    ]
