# Generated by Django 4.1.7 on 2023-04-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0009_alter_rss_feed_temp_title_alter_rss_feed_url_feedurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dr_Vikram_Sethi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('feedName', models.TextField()),
                ('title', models.TextField(unique=True)),
                ('publishedDate', models.DateTimeField()),
                ('link', models.TextField()),
                ('summary', models.TextField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
